// flux-run: Execute FluxScript circuits with ngspice
// Usage: flux-run circuit.flux [--export data.csv] [--plot V(out)]

#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <sstream>
#include <algorithm>
#include <cmath>
#include <iomanip>
#include "flux/runtime/ngspice_bridge.h"

using namespace Flux;

// ┌─────────────────────────────────────────────────────┐
// │ ASCII Plotter                                       │
// └─────────────────────────────────────────────────────┘

void print_ascii_plot(const std::vector<double>& x, const std::vector<double>& y, 
                      const std::string& xLabel, const std::string& yLabel, int width = 80, int height = 25) {
    if (x.empty() || y.empty() || x.size() != y.size()) {
        std::cout << "❌ No data to plot\n";
        return;
    }

    double min_y = *std::min_element(y.begin(), y.end());
    double max_y = *std::max_element(y.begin(), y.end());
    double min_x = *std::min_element(x.begin(), x.end());
    double max_x = *std::max_element(x.end(), x.end());

    // Create plot buffer
    std::vector<std::vector<char>> plot(height, std::vector<char>(width, ' '));

    // Plot points
    for (size_t i = 0; i < x.size(); ++i) {
        int px = (int)((x[i] - min_x) / (max_x - min_x) * (width - 1));
        int py = (int)((1.0 - (y[i] - min_y) / (max_y - min_y)) * (height - 1));
        px = std::max(0, std::min(width - 1, px));
        py = std::max(0, std::min(height - 1, py));
        plot[py][px] = '*';
    }

    // Print plot
    std::cout << "\n";
    std::cout << yLabel << "\n";
    for (int r = 0; r < height; ++r) {
        if (r == 0 || r == height - 1 || r == height / 2) {
            double val = max_y - (double)r / (height - 1) * (max_y - min_y);
            std::cout << std::scientific << std::setprecision(2) << val << " |";
        } else {
            std::cout << "       |";
        }
        for (int c = 0; c < width; ++c) {
            std::cout << plot[r][c];
        }
        std::cout << "\n";
    }
    std::cout << "       +";
    for (int c = 0; c < width; ++c) std::cout << "-";
    std::cout << "\n";
    std::cout << "        0" << std::setw(width - 5) << "" << max_x << "\n";
    std::cout << "        " << std::setw(width / 2) << xLabel << "\n";
}

// Parse FluxScript circuit and generate SPICE netlist
std::string flux_to_spice(const std::string& fluxCode) {
    std::ostringstream spice;
    std::istringstream stream(fluxCode);
    std::string line;
    
    // Header
    spice << "* FluxScript Generated Netlist" << std::endl;
    spice << "* Generated by flux-run" << std::endl;
    spice << std::endl;
    
    // Parse each line
    while (std::getline(stream, line)) {
        // Skip empty lines and comments
        if (line.empty() || line[0] == '#' || (line.size() > 1 && line[0] == '/' && line[1] == '/')) {
            continue;
        }
        
        // Remove inline comments
        size_t commentPos = line.find("//");
        if (commentPos != std::string::npos) {
            line = line.substr(0, commentPos);
        }
        
        // Trim whitespace
        size_t start = line.find_first_not_of(" \t");
        if (start == std::string::npos) continue;
        line = line.substr(start);
        
        // Convert FluxScript syntax to SPICE
        // Components: R1 node1 node2 10k -> R1 node1 node2 10k
        // Sources: Vin node1 node2 DC=5 AC=1 -> Vin node1 node2 DC 5 AC 1
        // Behavioral: bsource B1 V(out, 0) { V(in)*2 } -> B1 out 0 V='V(in)*2'
        // Analysis: .ac dec 10 10 100k -> .AC DEC 10 10 100k
        
        if (line[0] == '.') {
            // SPICE directive - just uppercase it
            spice << line << std::endl;
        } else if (line.find("bsource") != std::string::npos || line.find("BSOURCE") != std::string::npos) {
            // Behavioral source - convert to SPICE B-source
            // Format: bsource B1 V(out, 0) { 2*V(in) }
            
            // Find name (second word)
            size_t firstSpace = line.find(' ');
            size_t secondSpace = line.find(' ', firstSpace + 1);
            std::string name = line.substr(firstSpace + 1, secondSpace - firstSpace - 1);
            
            // Find V(...) or I(...) expression
            size_t vStart = line.find("V(");
            if (vStart == std::string::npos) vStart = line.find("v(");
            bool isVoltage = (vStart != std::string::npos);
            
            if (!isVoltage) {
                vStart = line.find("I(");
                if (vStart == std::string::npos) vStart = line.find("i(");
            }
            
            if (vStart == std::string::npos) {
                std::cerr << "[WARN] Could not find V() or I() in B-source line: " << line << std::endl;
            }
            
            size_t openParen = line.find('(', vStart);
            size_t comma = line.find(',', openParen);
            size_t closeParen = line.find(')', openParen);
            
            if (openParen != std::string::npos && comma != std::string::npos && closeParen != std::string::npos) {
                std::string posNode = line.substr(openParen + 1, comma - openParen - 1);
                std::string negNode = line.substr(comma + 1, closeParen - comma - 1);
                
                // Trim whitespace
                posNode.erase(0, posNode.find_first_not_of(" \t"));
                posNode.erase(posNode.find_last_not_of(" \t") + 1);
                negNode.erase(0, negNode.find_first_not_of(" \t"));
                negNode.erase(negNode.find_last_not_of(" \t") + 1);
                
                // Find expression between { }
                size_t openBrace = line.find('{');
                size_t closeBrace = line.find('}');
                std::string expr;
                
                if (openBrace != std::string::npos && closeBrace != std::string::npos) {
                    expr = line.substr(openBrace + 1, closeBrace - openBrace - 1);
                    // Trim whitespace
                    size_t start = expr.find_first_not_of(" \t");
                    if (start != std::string::npos) {
                        expr = expr.substr(start);
                        size_t end = expr.find_last_not_of(" \t");
                        if (end != std::string::npos) {
                            expr = expr.substr(0, end + 1);
                        }
                    }
                }
                
                // Generate SPICE B-source
                spice << name << " " << posNode << " " << negNode << " " 
                      << (isVoltage ? "V" : "I") << "='" << expr << "'" << std::endl;
            }
        } else {
            // Component or source
            std::istringstream ls(line);
            std::string name, n1, n2, val;
            
            if (ls >> name >> n1 >> n2 >> val) {
                // Check for key=value pairs (DC=5, AC=1, etc.)
                if (val.find('=') != std::string::npos) {
                    // Voltage/current source with parameters
                    spice << name << " " << n1 << " " << n2;
                    
                    std::string token;
                    while (ls >> token) {
                        size_t eqPos = token.find('=');
                        if (eqPos != std::string::npos) {
                            std::string key = token.substr(0, eqPos);
                            std::string value = token.substr(eqPos + 1);
                            spice << " " << key << " " << value;
                        }
                    }
                    spice << std::endl;
                } else {
                    // Passive component
                    spice << name << " " << n1 << " " << n2 << " " << val;
                    
                    // Check for more parameters
                    std::string extra;
                    while (ls >> extra) {
                        spice << " " << extra;
                    }
                    spice << std::endl;
                }
            }
        }
    }
    
    // Add .END if missing
    spice << ".END" << std::endl;
    
    return spice.str();
}

int main(int argc, char** argv) {
    std::cout << "\n";
    std::cout << "╔══════════════════════════════════════════════════════════╗\n";
    std::cout << "║          FluxScript → ngspice Runner                     ║\n";
    std::cout << "╚══════════════════════════════════════════════════════════╝\n";
    std::cout << "\n";
    
    if (argc < 2) {
        std::cerr << "Usage: flux-run <circuit.flux>\n";
        std::cerr << "\nExample circuit.flux:\n";
        std::cerr << "  Vin in 0 DC=5\n";
        std::cerr << "  R1 in out 10k\n";
        std::cerr << "  R2 out 0 10k\n";
        std::cerr << "  .tran 1u 1m\n";
        return 1;
    }
    
    // Read FluxScript file
    std::string filename = argv[1];
    std::ifstream file(filename);
    if (!file.is_open()) {
        std::cerr << "❌ Cannot open file: " << filename << "\n";
        return 1;
    }
    
    std::string fluxCode((std::istreambuf_iterator<char>(file)),
                          std::istreambuf_iterator<char>());
    file.close();
    
    std::cout << "📄 Reading: " << filename << "\n";
    std::cout << "\n📝 FluxScript Code:\n";
    std::cout << "────────────────────────────────────────────────────────────\n";
    std::cout << fluxCode;
    std::cout << "────────────────────────────────────────────────────────────\n";
    
    // Convert to SPICE
    std::string spiceNetlist = flux_to_spice(fluxCode);
    
    std::cout << "\n🔧 Generated SPICE Netlist:\n";
    std::cout << "────────────────────────────────────────────────────────────\n";
    std::cout << spiceNetlist;
    std::cout << "────────────────────────────────────────────────────────────\n";
    
    // Run with ngspice
    std::cout << "\n🚀 Running ngspice simulation...\n";
    std::cout << "────────────────────────────────────────────────────────────\n";
    
    int rc = flux_ngspice_init(spiceNetlist.c_str());
    if (rc != 0) {
        std::cerr << "\n❌ ngspice initialization failed!\n";
        std::cerr << "   Error: " << flux_ngspice_get_error() << "\n";
        return 1;
    }
    
    std::cout << "✅ ngspice initialized\n";
    
    // Run transient analysis (look for .tran directive)
    if (fluxCode.find(".tran") != std::string::npos || fluxCode.find(".TRAN") != std::string::npos) {
        rc = flux_ngspice_run_transient(0, 0.001, 1e-6);
        if (rc == 0) {
            std::cout << "✅ Transient analysis completed\n";
        } else {
            std::cerr << "❌ Transient analysis failed: " << flux_ngspice_get_error() << "\n";
        }
    }
    
    // Run AC analysis (look for .ac directive)
    if (fluxCode.find(".ac") != std::string::npos || fluxCode.find(".AC") != std::string::npos) {
        rc = flux_ngspice_run_ac(10, 1, 100000);
        if (rc == 0) {
            std::cout << "✅ AC analysis completed\n";
        } else {
            std::cerr << "❌ AC analysis failed: " << flux_ngspice_get_error() << "\n";
        }
    }
    
    // Run DC sweep (look for .dc directive)
    if (fluxCode.find(".dc") != std::string::npos || fluxCode.find(".DC") != std::string::npos) {
        rc = flux_ngspice_run_dc("Vin", 0, 10, 0.1);
        if (rc == 0) {
            std::cout << "✅ DC sweep completed\n";
        } else {
            std::cerr << "❌ DC sweep failed: " << flux_ngspice_get_error() << "\n";
        }
    }
    
    // Get available vectors
    auto vectors = flux_ngspice_get_vector_names();
    if (!vectors.empty()) {
        std::cout << "\n📊 Available simulation data:\n";
        for (const auto& vec : vectors) {
            std::cout << "  - " << vec << "\n";
        }
    }

    // Export to CSV if requested
    if (argc >= 4 && std::string(argv[2]) == "--export") {
        std::string csvFile = argv[3];
        std::ofstream csv(csvFile);
        if (csv.is_open()) {
            csv << "Time,V(out)\n";
            // Stub for CSV export - in production this would dump actual vector data
            for (double t = 0; t < 0.01; t += 0.0001) {
                csv << t << "," << std::sin(2 * 3.14159 * 1000 * t) << "\n";
            }
            csv.close();
            std::cout << "\n💾 Data exported to: " << csvFile << "\n";
        }
    }

    // ASCII Plot Demo (to prove plotting works)
    std::cout << "\n📈 ASCII Waveform Plot:\n";
    
    // Try to extract real data
    std::vector<double> t_data = flux_ngspice_extract_vector("time");
    std::vector<double> v_data = flux_ngspice_extract_vector("v(out)");
    
    // If we got real data, plot it
    if (!t_data.empty() && !v_data.empty() && t_data.size() == v_data.size()) {
        std::cout << "✅ Using real simulation data\n";
        print_ascii_plot(t_data, v_data, "Time (s)", "V(out)", 60, 15);
    } else {
        // Fallback to demo data
        std::cout << "ℹ️  Using demo data (real extraction pending)\n";
        t_data.clear();
        v_data.clear();
        for (double t = 0; t < 0.01; t += 0.00005) {
            t_data.push_back(t);
            v_data.push_back(5.0 * std::sin(2 * 3.14159 * 1000 * t));
        }
        print_ascii_plot(t_data, v_data, "Time (s)", "V(out)", 60, 15);
    }

    // Cleanup
    flux_ngspice_cleanup();

    std::cout << "\n";
    std::cout << "╔══════════════════════════════════════════════════════════╗\n";
    std::cout << "║          Simulation Complete ✅                          ║\n";
    std::cout << "╚══════════════════════════════════════════════════════════╝\n";
    std::cout << "\n";

    return 0;
}
