/* Copyright 2026 Janada Sroor
 SPDX-License-Identifier: Apache-2.0
 http://www.apache.org/licenses/LICENSE-2.0
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
     http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License. */

// flux-spice.cpp - FluxScript SPICE CLI Tool
// Generates SPICE netlists from FluxScript and interfaces with ngspice

#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

#include "flux/compiler/compiler_instance.h"
#include "flux/runtime/ngspice_bridge.h"

void printHelp()
{
    std::cout << "FluxScript SPICE CLI v1.0.0\n";
    std::cout << "============================\n\n";
    std::cout << "Usage: flux-spice [options] <script.flux>\n\n";
    std::cout << "Options:\n";
    std::cout << "  --netlist         Generate SPICE netlist only (default)\n";
    std::cout << "  --run             Run simulation (requires ngspice)\n";
    std::cout << "  --output <file>   Output file for results (CSV format)\n";
    std::cout << "  --tran <tstep> <tstop>  Transient analysis parameters\n";
    std::cout << "  --help            Show this help message\n";
    std::cout << "  --version         Show version information\n";
    std::cout << "\nExamples:\n";
    std::cout << "  flux-spice circuit.flux                    # Generate netlist\n";
    std::cout << "  flux-spice --run circuit.flux              # Run simulation\n";
    std::cout << "  flux-spice --output results.csv circuit.flux  # Save results\n";
    std::cout << "  flux-spice --tran 1u 1m circuit.flux       # Set analysis params\n";
}

void printVersion()
{
    std::cout << "FluxScript SPICE CLI v1.0.0\n";
    std::cout << "  FluxScript Compiler: 1.0.0\n";
    std::cout << "  SPICE Integration: Phase 1 (State Management)\n";
    std::cout << "  ngspice Bridge: Stub Implementation\n";
}

std::string readFile(const std::string& path)
{
    std::ifstream file(path);
    if (!file.is_open()) {
        throw std::runtime_error("Cannot open file: " + path);
    }

    std::stringstream buffer;
    buffer << file.rdbuf();
    return buffer.str();
}

std::string generateSimpleNetlist(const std::string& code)
{
    // Simplified netlist generator for demonstration
    // Full implementation would parse AST and generate proper SPICE

    std::ostringstream netlist;

    netlist << "* FluxScript Generated Netlist\n";
    netlist << "* Source: " << "script.flux" << "\n";
    netlist << "* Generated by flux-spice CLI\n";
    netlist << "\n";

    // Add standard includes
    netlist << "* Include libraries\n";
    netlist << ".INCLUDE standard_models.lib\n";
    netlist << "\n";

    // Add parameters (would be extracted from FluxScript param declarations)
    netlist << "* Parameters\n";
    netlist << ".PARAM R=1k C=1u VCC=5\n";
    netlist << "\n";

    // Add initial conditions (would be extracted from ic declarations)
    netlist << "* Initial Conditions\n";
    netlist << ".IC V(out)=0 V(cap)=0\n";
    netlist << "\n";

    // Add behavioral models (would be extracted from update() functions)
    netlist << "* Behavioral Models\n";
    netlist << "B1 out 0 V={V(in) * gain}\n";
    netlist << ".PARAM gain=10\n";
    netlist << "\n";

    // Add analysis commands (would be extracted from analysis declarations)
    netlist << "* Analysis Commands\n";
    netlist << ".TRAN 1u 1m\n";
    netlist << ".PROBE V(out) V(in) I(R1)\n";
    netlist << ".MEAS vout_max MAX V(out)\n";
    netlist << ".MEAS vout_avg AVG V(out)\n";
    netlist << "\n";

    netlist << ".END\n";

    return netlist.str();
}

int main(int argc, char** argv)
{
    std::cout << "FluxScript SPICE CLI v1.0.0\n";
    std::cout << "============================\n\n";

    if (argc < 2) {
        printHelp();
        return 0;
    }

    // Parse arguments
    std::string inputFile;
    bool generateNetlistOnly = true;
    bool runSimulation = false;
    std::string outputFile;
    double tStep = 1e-6;
    double tStop = 1e-3;

    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];

        if (arg == "--help" || arg == "-h") {
            printHelp();
            return 0;
        } else if (arg == "--version" || arg == "-v") {
            printVersion();
            return 0;
        } else if (arg == "--netlist") {
            generateNetlistOnly = true;
        } else if (arg == "--run") {
            runSimulation = true;
            generateNetlistOnly = false;
        } else if (arg == "--output" && i + 1 < argc) {
            outputFile = argv[++i];
        } else if (arg == "--tran" && i + 2 < argc) {
            try {
                tStep = std::stod(argv[++i]);
                tStop = std::stod(argv[++i]);
            } catch (...) {
                std::cerr << "Error: Invalid transient parameters\n";
                return 1;
            }
        } else if (arg[0] != '-') {
            inputFile = arg;
        } else {
            std::cerr << "Unknown option: " << arg << "\n";
            printHelp();
            return 1;
        }
    }

    if (inputFile.empty()) {
        std::cerr << "Error: No input file specified\n";
        printHelp();
        return 1;
    }

    std::cout << "Input file: " << inputFile << "\n";

    // Read input file
    std::string code;
    try {
        code = readFile(inputFile);
    } catch (const std::exception& e) {
        std::cerr << "Error: " << e.what() << "\n";
        return 1;
    }

    std::cout << "Code size: " << code.size() << " bytes\n\n";

    // Compile FluxScript (validates syntax)
    std::cout << "Compiling FluxScript...\n";

    Flux::CompilerOptions options;
    options.inputName = inputFile;
    options.moduleName = "spice_module";

    Flux::CompilerInstance compiler(options);
    std::string error;

    auto artifacts = compiler.compileToIR(code, &error);
    if (!artifacts) {
        std::cerr << "Compilation Error: " << error << "\n";
        return 1;
    }

    std::cout << " Compilation successful\n\n";

    // Generate netlist
    std::cout << "Generating SPICE netlist...\n";

    std::string netlist = generateSimpleNetlist(code);

    // Write netlist to file
    std::string netlistFile = inputFile + ".cir";
    std::ofstream netfile(netlistFile);
    if (netfile.is_open()) {
        netfile << netlist;
        netfile.close();
        std::cout << " Generated netlist: " << netlistFile << "\n";
    } else {
        std::cerr << "Error: Cannot write netlist file\n";
        return 1;
    }

    if (generateNetlistOnly) {
        std::cout << "\nNetlist generation complete.\n";
        std::cout << "To run simulation: flux-spice --run " << inputFile << "\n";
        return 0;
    }

    // Run simulation with ngspice
    if (runSimulation) {
        std::cout << "\nRunning ngspice simulation...\n";
        std::cout << "  tstep = " << tStep << " s\n";
        std::cout << "  tstop = " << tStop << " s\n";

        // Initialize ngspice bridge
        int result = Flux::flux_ngspice_init(netlist.c_str());
        if (result != 0) {
            std::cerr << "Error: Failed to initialize ngspice bridge\n";
            std::cerr << "Note: Full ngspice integration requires ngspice-shared library\n";
            std::cout << "\nRunning stub simulation for demonstration...\n";
        }

        // Run transient analysis
        result = Flux::flux_ngspice_run_transient(0.0, tStop, tStep);
        if (result != 0) {
            std::cerr << "Error: Simulation failed\n";
            Flux::flux_ngspice_cleanup();
            return 1;
        }

        std::cout << " Simulation completed\n";

        // Get results
        int vecSize = Flux::flux_ngspice_get_vector_size("v(out)");
        std::cout << " Output vector size: " << vecSize << " points\n";

        // Write results to file
        if (!outputFile.empty()) {
            std::cout << "\nWriting results to: " << outputFile << "\n";

            std::ofstream outfile(outputFile);
            if (outfile.is_open()) {
                outfile << "time,v(out)\n";
                for (int i = 0; i < std::min(vecSize, 100); ++i) {
                    double time = i * tStep;
                    double vout = Flux::flux_ngspice_get_vector("v(out)", i);
                    outfile << time << "," << vout << "\n";
                }
                outfile.close();
                std::cout << " Results written successfully\n";
            } else {
                std::cerr << "Warning: Cannot write output file\n";
            }
        }

        // Cleanup
        Flux::flux_ngspice_cleanup();
    }

    std::cout << "\nDone.\n";
    return 0;
}
