/* Copyright 2026 Janada Sroor
 SPDX-License-Identifier: Apache-2.0
 http://www.apache.org/licenses/LICENSE-2.0
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
     http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License. */

#include "flux/compiler/netlist_generator.h"
#include "flux/compiler/lexer.h"
#include "flux/compiler/component_modeling_ast.h"
#include <sstream>
#include <cmath>

namespace Flux {

NetlistGenerator::NetlistGenerator() : m_nodeCounter(1) {}
NetlistGenerator::~NetlistGenerator() {}

static std::string analysisTypeToString(AnalysisType type) {
    switch (type) {
        case AnalysisType::TRAN: return "tran";
        case AnalysisType::DC: return "dc";
        case AnalysisType::AC: return "ac";
        case AnalysisType::NOISE: return "noise";
        case AnalysisType::OP: return "op";
        case AnalysisType::TF: return "tf";
        case AnalysisType::SENS: return "sens";
        case AnalysisType::FOURIER: return "fourier";
    }
    return "unknown";
}

static std::string measureTypeToString(MeasureType type) {
    switch (type) {
        case MeasureType::MAX: return "MAX";
        case MeasureType::MIN: return "MIN";
        case MeasureType::AVG: return "AVG";
        case MeasureType::RMS: return "RMS";
        case MeasureType::TRIG: return "TRIG";
        case MeasureType::TARG: return "TARG";
        case MeasureType::WHEN: return "WHEN";
        case MeasureType::FIND: return "FIND";
        case MeasureType::DERIV: return "DERIV";
        case MeasureType::INTEG: return "INTEG";
    }
    return "UNKNOWN";
}

std::string NetlistGenerator::generateNetlist(
    const std::vector<std::unique_ptr<FunctionAST>>& functions,
    const std::vector<std::unique_ptr<SubcktAST>>& subckts,
    const std::vector<std::unique_ptr<ModelAST>>& models,
    const std::vector<std::unique_ptr<AnalysisExprAST>>& analyses,
    const std::vector<std::unique_ptr<MeasureExprAST>>& measures) {
    
    m_netlist.str("");
    m_netlist.clear();
    
    // Header
    m_netlist << "* FluxScript Generated Netlist\n";
    m_netlist << "* Generated by FluxScript Compiler\n";
    m_netlist << "\n";
    
    // Models
    for (const auto& model : models) {
        m_netlist << generateModelCard(model.get());
    }
    
    // Subcircuits
    for (const auto& subckt : subckts) {
        m_netlist << generateSubcktCard(subckt.get());
    }
    
    // Measures
    for (const auto& measure : measures) {
        m_netlist << generateMeasureCard(measure.get());
    }
    
    // Analysis
    for (const auto& analysis : analyses) {
        m_netlist << generateAnalysisCard(analysis.get());
    }
    
    m_netlist << "\n.END\n";
    
    return m_netlist.str();
}

std::string NetlistGenerator::generateTitle(const std::string& title) {
    return "* " + title + "\n";
}

std::string NetlistGenerator::generateInclude(const std::string& file) {
    return ".INCLUDE " + file + "\n";
}

std::string NetlistGenerator::generateLib(const std::string& lib) {
    return ".LIB " + lib + "\n";
}

std::string NetlistGenerator::generateParam(const std::string& name, double value) {
    return ".PARAM " + name + "=" + valueToSpice(value) + "\n";
}

std::string NetlistGenerator::generateAnalysisCard(const AnalysisExprAST* analysis) {
    if (!analysis) return "";
    
    std::ostringstream oss;
    oss << "." << analysisTypeToString(analysis->getAnalysisType());
    
    for (const auto& [name, value] : analysis->getParameters()) {
        oss << " " << name << "=" << expressionToSpice(value.get());
    }
    
    oss << "\n";
    return oss.str();
}

std::string NetlistGenerator::generateMeasureCard(const MeasureExprAST* measure) {
    if (!measure) return "";
    
    std::ostringstream oss;
    oss << ".MEAS " << measure->getName() << " " << measureTypeToString(measure->getMeasureType()) 
        << " " << expressionToSpice(measure->getExpression());
    
    for (const auto& [key, value] : measure->getParameters()) {
        oss << " " << key << "=" << expressionToSpice(value.get());
    }
    
    oss << "\n";
    return oss.str();
}

std::string NetlistGenerator::generateProbeCard(const ProbeDeclAST* probe) {
    if (!probe) return "";
    
    std::ostringstream oss;
    oss << ".PROBE " << probe->getVariableName() << "\n";
    return oss.str();
}

std::string NetlistGenerator::generateSaveCard(const std::vector<std::string>& signalNames) {
    std::ostringstream oss;
    oss << ".SAVE";
    
    for (const auto& signal : signalNames) {
        oss << " " << signal;
    }
    
    oss << "\n";
    return oss.str();
}

std::string NetlistGenerator::generateSubcktCard(const SubcktAST* subckt) {
    if (!subckt) return "";
    
    std::ostringstream oss;
    oss << ".SUBCKT " << subckt->getName();
    
    for (const auto& pin : subckt->getPins()) {
        oss << " " << pin;
    }
    
    for (const auto& [name, value] : subckt->getParameters()) {
        oss << " " << name << "=" << expressionToSpice(value.get());
    }
    oss << "\n";
    
    // Subcircuit body
    for (const auto& stmt : subckt->getBody()) {
        if (auto* bsource = dynamic_cast<const BSourceExprAST*>(stmt.get())) {
            oss << "B" << bsource->getName() << " " << bsource->getPositiveNode() << " " 
                << bsource->getNegativeNode() << " " << (bsource->isCurrentSource() ? "I" : "V") 
                << "={" << expressionToSpice(bsource->getExpression()) << "}\n";
        } else if (auto* esource = dynamic_cast<const ESourceExprAST*>(stmt.get())) {
            oss << "E" << esource->getName() << " " << esource->getPositiveNode() << " " 
                << esource->getNegativeNode() << " " << esource->getControlPosNode() << " " 
                << esource->getControlNegNode() << " " << expressionToSpice(esource->getGain()) << "\n";
        } else if (auto* fsource = dynamic_cast<const FSourceExprAST*>(stmt.get())) {
            oss << "F" << fsource->getName() << " " << fsource->getPositiveNode() << " " 
                << fsource->getNegativeNode() << " " << fsource->getVoltageSourceName() << " " 
                << expressionToSpice(fsource->getGain()) << "\n";
        } else if (auto* gsource = dynamic_cast<const GSourceExprAST*>(stmt.get())) {
            oss << "G" << gsource->getName() << " " << gsource->getPositiveNode() << " " 
                << gsource->getNegativeNode() << " " << gsource->getControlPosNode() << " " 
                << gsource->getControlNegNode() << " " << expressionToSpice(gsource->getTransconductance()) << "\n";
        } else if (auto* hsource = dynamic_cast<const HSourceExprAST*>(stmt.get())) {
            oss << "H" << hsource->getName() << " " << hsource->getPositiveNode() << " " 
                << hsource->getNegativeNode() << " " << hsource->getVoltageSourceName() << " " 
                << expressionToSpice(hsource->getTransresistance()) << "\n";
        } else if (auto* model = dynamic_cast<const ModelAST*>(stmt.get())) {
            oss << generateModelCard(model);
        } else if (auto* sub = dynamic_cast<const SubcktAST*>(stmt.get())) {
            oss << generateSubcktCard(sub);
        } else if (auto* inst = dynamic_cast<const SubcktInstanceAST*>(stmt.get())) {
            oss << "X" << inst->getInstanceName();
            for (const auto& node : inst->getNodes()) oss << " " << node;
            oss << " " << inst->getSubcktName();
            for (const auto& [name, val] : inst->getParameters()) oss << " " << name << "=" << val;
            oss << "\n";
        } else if (auto* param = dynamic_cast<const ParamExprAST*>(stmt.get())) {
            oss << ".PARAM " << param->getName() << "=" << expressionToSpice(param->getValue()) << "\n";
        } else if (auto* ic = dynamic_cast<const ICExprAST*>(stmt.get())) {
            oss << ".IC V(" << ic->getNodeName() << ")=" << expressionToSpice(ic->getValue()) << "\n";
        }
    }
    
    oss << ".ENDS " << subckt->getName() << "\n";
    return oss.str();
}

std::string NetlistGenerator::generateModelCard(const ModelAST* model) {
    if (!model) return "";
    
    std::ostringstream oss;
    oss << ".MODEL " << model->getName() << " " << model->getModelType() << " (\n";
    
    bool first = true;
    for (const auto& [name, value] : model->getParameters()) {
        if (!first) oss << "\n";
        oss << "  " << name << "=" << expressionToSpice(value.get());
        first = false;
    }
    
    oss << "\n)\n";
    return oss.str();
}

std::string NetlistGenerator::generateEnds() {
    return ".ENDS\n";
}

std::string NetlistGenerator::generateResistor(const std::string& name, const std::string& n1, 
                                                const std::string& n2, double value) {
    return "R" + name + " " + n1 + " " + n2 + " " + valueToSpice(value) + "\n";
}

std::string NetlistGenerator::generateCapacitor(const std::string& name, const std::string& n1,
                                                 const std::string& n2, double value) {
    return "C" + name + " " + n1 + " " + n2 + " " + valueToSpice(value) + "\n";
}

std::string NetlistGenerator::generateInductor(const std::string& name, const std::string& n1,
                                                const std::string& n2, double value) {
    return "L" + name + " " + n1 + " " + n2 + " " + valueToSpice(value) + "\n";
}

std::string NetlistGenerator::generateDiode(const std::string& name, const std::string& n1,
                                             const std::string& n2, const std::string& model) {
    return "D" + name + " " + n1 + " " + n2 + " " + model + "\n";
}

std::string NetlistGenerator::generateBJT(const std::string& name, const std::string& nc,
                                           const std::string& nb, const std::string& ne,
                                           const std::string& ns, const std::string& model) {
    return "Q" + name + " " + nc + " " + nb + " " + ne + " " + ns + " " + model + "\n";
}

std::string NetlistGenerator::generateMOSFET(const std::string& name, const std::string& nd,
                                              const std::string& ng, const std::string& ns,
                                              const std::string& nb, const std::string& model) {
    return "M" + name + " " + nd + " " + ng + " " + ns + " " + nb + " " + model + "\n";
}

std::string NetlistGenerator::generateBSource(const std::string& name, 
                                               const std::vector<std::string>& nodes,
                                               const std::string& type,
                                               const std::string& expression) {
    if (nodes.size() < 2) return "";
    
    std::ostringstream oss;
    oss << "B" << name << " " << nodes[0] << " " << nodes[1] 
        << " " << type << "={" << expression << "}\n";
    return oss.str();
}

std::string NetlistGenerator::generateBVoltage(const std::string& name,
                                                const std::string& nPlus,
                                                const std::string& nMinus,
                                                const std::string& expression) {
    return generateBSource(name, {nPlus, nMinus}, "V", expression);
}

std::string NetlistGenerator::generateBCurrent(const std::string& name,
                                                const std::string& nPlus,
                                                const std::string& nMinus,
                                                const std::string& expression) {
    return generateBSource(name, {nPlus, nMinus}, "I", expression);
}

// E-source (Voltage-Controlled Voltage Source)
std::string NetlistGenerator::generateESource(const std::string& name,
                                               const std::string& nPlus,
                                               const std::string& nMinus,
                                               const std::string& cnPlus,
                                               const std::string& cnMinus,
                                               double gain) {
    std::ostringstream oss;
    oss << "E" << name << " " << nPlus << " " << nMinus << " "
        << cnPlus << " " << cnMinus << " " << gain << "\n";
    return oss.str();
}

// F-source (Current-Controlled Current Source)
std::string NetlistGenerator::generateFSource(const std::string& name,
                                               const std::string& nPlus,
                                               const std::string& nMinus,
                                               const std::string& vSourceName,
                                               double gain) {
    std::ostringstream oss;
    oss << "F" << name << " " << nPlus << " " << nMinus << " "
        << vSourceName << " " << gain << "\n";
    return oss.str();
}

// G-source (Voltage-Controlled Current Source)
std::string NetlistGenerator::generateGSource(const std::string& name,
                                               const std::string& nPlus,
                                               const std::string& nMinus,
                                               const std::string& cnPlus,
                                               const std::string& cnMinus,
                                               double gain) {
    std::ostringstream oss;
    oss << "G" << name << " " << nPlus << " " << nMinus << " "
        << cnPlus << " " << cnMinus << " " << gain << "\n";
    return oss.str();
}

// H-source (Current-Controlled Voltage Source)
std::string NetlistGenerator::generateHSource(const std::string& name,
                                               const std::string& nPlus,
                                               const std::string& nMinus,
                                               const std::string& vSourceName,
                                               double gain) {
    std::ostringstream oss;
    oss << "H" << name << " " << nPlus << " " << nMinus << " "
        << vSourceName << " " << gain << "\n";
    return oss.str();
}

std::string NetlistGenerator::generateSubcktInstance(const std::string& name,
                                                     const std::string& subcktName,
                                                     const std::vector<std::string>& nodes,
                                                     const std::map<std::string, double>& params) {
    std::ostringstream oss;
    oss << "X" << name;
    for (const auto& node : nodes) {
        oss << " " << node;
    }
    oss << " " << subcktName;
    for (const auto& [key, val] : params) {
        oss << " " << key << "=" << valueToSpice(val);
    }
    oss << "\n";
    return oss.str();
}

std::string NetlistGenerator::getInternalNode(const std::string& name) {
    auto it = m_nodeMap.find(name);
    if (it != m_nodeMap.end()) {
        return "n" + std::to_string(it->second);
    }
    
    int nodeNum = m_nodeCounter++;
    m_nodeMap[name] = nodeNum;
    return "n" + std::to_string(nodeNum);
}

std::string NetlistGenerator::expressionToSpice(const ExprAST* expr) {
    if (!expr) return "0";
    
    if (auto* num = dynamic_cast<const NumberExprAST*>(expr)) {
        return valueToSpice(num->getValue());
    }
    
    if (auto* var = dynamic_cast<const VariableExprAST*>(expr)) {
        return var->getName();
    }

    if (auto* bin = dynamic_cast<const BinaryExprAST*>(expr)) {
        return "(" + expressionToSpice(bin->getLHS()) + " " + 
               Lexer::tokenSpelling(bin->getOp()) + " " + 
               expressionToSpice(bin->getRHS()) + ")";
    }

    if (auto* un = dynamic_cast<const UnaryExprAST*>(expr)) {
        return "(" + Lexer::tokenSpelling(un->getOp()) + 
               expressionToSpice(un->getOperand()) + ")";
    }

    if (auto* call = dynamic_cast<const CallExprAST*>(expr)) {
        std::string res = call->getCallee() + "(";
        for (size_t i = 0; i < call->getArgs().size(); ++i) {
            if (i > 0) res += ", ";
            res += expressionToSpice(call->getArgs()[i].get());
        }
        res += ")";
        return res;
    }

    if (auto* volt = dynamic_cast<const VoltageExprAST*>(expr)) {
        return "V(" + volt->getNodeName() + ")";
    }

    if (auto* curr = dynamic_cast<const CurrentExprAST*>(expr)) {
        return "I(" + curr->getBranchName() + ")";
    }

    if (auto* param = dynamic_cast<const ParameterExprAST*>(expr)) {
        return param->getParamName();
    }
    
    if (auto* block = dynamic_cast<const BlockExprAST*>(expr)) {
        if (block->getStatements().empty()) return "0";
        // For SPICE expressions, we take the last expression in the block
        return expressionToSpice(block->getStatements().back().get());
    }
    
    if (auto* assign = dynamic_cast<const AssignExprAST*>(expr)) {
        // In SPICE B-sources, V=V is redundant if already in card, but let's just return RHS
        return expressionToSpice(assign->getValueExpr());
    }
    
    // For more complex expressions, return 0 as placeholder for now
    return "0";
}

std::string NetlistGenerator::valueToSpice(double value) {
    if (value == 0) return "0";
    
    std::ostringstream oss;
    double absVal = std::abs(value);
    std::string sign = (value < 0) ? "-" : "";
    
    if (absVal >= 1e12) {
        oss << sign << (absVal / 1e12) << "T";
    } else if (absVal >= 1e9) {
        oss << sign << (absVal / 1e9) << "G";
    } else if (absVal >= 1e6) {
        oss << sign << (absVal / 1e6) << "Meg";
    } else if (absVal >= 1e3) {
        oss << sign << (absVal / 1e3) << "k";
    } else if (absVal >= 1) {
        oss << sign << absVal;
    } else if (absVal >= 1e-3) {
        oss << sign << (absVal * 1e3) << "m";
    } else if (absVal >= 1e-6) {
        oss << sign << (absVal * 1e6) << "u";
    } else if (absVal >= 1e-9) {
        oss << sign << (absVal * 1e9) << "n";
    } else if (absVal >= 1e-12) {
        oss << sign << (absVal * 1e12) << "p";
    } else if (absVal >= 1e-15) {
        oss << sign << (absVal * 1e15) << "f";
    } else {
        oss << value;
    }
    
    return oss.str();
}

} // namespace Flux
