#include "flux/compiler/netlist_generator.h"

namespace Flux {

NetlistGenerator::NetlistGenerator() : m_nodeCounter(100) {}

NetlistGenerator::~NetlistGenerator() {}

std::string NetlistGenerator::generateNetlist(
    const std::vector<std::unique_ptr<FunctionAST>>& functions,
    const std::vector<std::unique_ptr<SubcktAST>>& subckts,
    const std::vector<std::unique_ptr<ModelAST>>& models,
    const std::vector<std::unique_ptr<AnalysisDeclAST>>& analyses) {
    
    m_netlist.str("");
    m_netlist.clear();
    
    // Header
    m_netlist << "* FluxScript Generated Netlist\n";
    m_netlist << "* Generated by FluxScript Compiler\n";
    m_netlist << "\n";
    
    // Models
    for (const auto& model : models) {
        m_netlist << generateModelCard(model.get());
    }
    m_netlist << "\n";
    
    // Subcircuits
    for (const auto& subckt : subckts) {
        m_netlist << generateSubcktCard(subckt.get());
    }
    m_netlist << "\n";
    
    // Analysis
    for (const auto& analysis : analyses) {
        m_netlist << generateAnalysisCard(analysis.get());
    }
    
    m_netlist << "\n.END\n";
    
    return m_netlist.str();
}

std::string NetlistGenerator::generateTitle(const std::string& title) {
    return "* " + title + "\n";
}

std::string NetlistGenerator::generateInclude(const std::string& file) {
    return ".INCLUDE " + file + "\n";
}

std::string NetlistGenerator::generateLib(const std::string& lib) {
    return ".LIB " + lib + "\n";
}

std::string NetlistGenerator::generateParam(const std::string& name, double value) {
    return ".PARAM " + name + "=" + valueToSpice(value) + "\n";
}

std::string NetlistGenerator::generateAnalysisCard(const AnalysisDeclAST* analysis) {
    if (!analysis) return "";
    
    std::ostringstream oss;
    const std::string& type = analysis->getType();
    const auto& params = analysis->getParams();
    
    if (type == "tran") {
        oss << ".TRAN";
        for (const auto& param : params) {
            // Would need to evaluate parameter expression
            oss << " 1u";  // Stub value
        }
        oss << "\n";
    } else if (type == "ac") {
        oss << ".AC";
        for (const auto& param : params) {
            oss << " DEC 10 1 1Meg";  // Stub value
        }
        oss << "\n";
    } else if (type == "dc") {
        oss << ".DC";
        for (const auto& param : params) {
            oss << " LIN 100 0 10";  // Stub value
        }
        oss << "\n";
    } else if (type == "op") {
        oss << ".OP\n";
    } else if (type == "tf") {
        oss << ".TF V(out) VIN\n";
    } else if (type == "sens") {
        oss << ".SENS V(out)\n";
    } else if (type == "fourier") {
        oss << ".FOUR 1k V(out)\n";
    } else if (type == "noise") {
        oss << ".NOISE V(out) VIN DEC 10 100 100k\n";
    }
    
    return oss.str();
}

std::string NetlistGenerator::generateMeasureCard(const MeasureDeclAST* measure) {
    if (!measure) return "";
    
    std::ostringstream oss;
    oss << ".MEAS " << measure->getName() << " " << measure->getFunction() 
        << " " << measure->getSignal();
    
    for (const auto& [key, value] : measure->Options) {
        oss << " " << key << "=" << value;
    }
    
    oss << "\n";
    return oss.str();
}

std::string NetlistGenerator::generateProbeCard(const ProbeDeclAST* probe) {
    if (!probe) return "";
    
    std::ostringstream oss;
    oss << ".PROBE";
    
    for (const auto& signal : probe->getSignals()) {
        oss << " " << signal;
    }
    
    oss << "\n";
    return oss.str();
}

std::string NetlistGenerator::generateSaveCard(const std::vector<std::string>& signals) {
    std::ostringstream oss;
    oss << ".SAVE";
    
    for (const auto& signal : signals) {
        oss << " " << signal;
    }
    
    oss << "\n";
    return oss.str();
}

std::string NetlistGenerator::generateSubcktCard(const SubcktAST* subckt) {
    if (!subckt) return "";
    
    std::ostringstream oss;
    oss << ".SUBCKT " << subckt->getName();
    
    for (const auto& pin : subckt->getPins()) {
        oss << " " << pin;
    }
    oss << "\n";
    
    // Subcircuit body would be generated here
    // For now, just add placeholder
    oss << "* Subcircuit body\n";
    
    oss << ".ENDS " << subckt->getName() << "\n";
    return oss.str();
}

std::string NetlistGenerator::generateModelCard(const ModelAST* model) {
    if (!model) return "";
    
    std::ostringstream oss;
    oss << ".MODEL " << model->getName() << " " << model->getType() << " (\n";
    
    bool first = true;
    for (const auto& [name, value] : model->getParams()) {
        if (!first) oss << "\n";
        oss << "  " << name << "=" << valueToSpice(value);
        first = false;
    }
    
    oss << "\n)\n";
    return oss.str();
}

std::string NetlistGenerator::generateEnds() {
    return ".ENDS\n";
}

std::string NetlistGenerator::generateResistor(const std::string& name, const std::string& n1, 
                                                const std::string& n2, double value) {
    return "R" + name + " " + n1 + " " + n2 + " " + valueToSpice(value) + "\n";
}

std::string NetlistGenerator::generateCapacitor(const std::string& name, const std::string& n1,
                                                 const std::string& n2, double value) {
    return "C" + name + " " + n1 + " " + n2 + " " + valueToSpice(value) + "\n";
}

std::string NetlistGenerator::generateInductor(const std::string& name, const std::string& n1,
                                                const std::string& n2, double value) {
    return "L" + name + " " + n1 + " " + n2 + " " + valueToSpice(value) + "\n";
}

std::string NetlistGenerator::generateDiode(const std::string& name, const std::string& n1,
                                             const std::string& n2, const std::string& model) {
    return "D" + name + " " + n1 + " " + n2 + " " + model + "\n";
}

std::string NetlistGenerator::generateBJT(const std::string& name, const std::string& nc,
                                           const std::string& nb, const std::string& ne,
                                           const std::string& ns, const std::string& model) {
    return "Q" + name + " " + nc + " " + nb + " " + ne + " " + ns + " " + model + "\n";
}

std::string NetlistGenerator::generateMOSFET(const std::string& name, const std::string& nd,
                                              const std::string& ng, const std::string& ns,
                                              const std::string& nb, const std::string& model) {
    return "M" + name + " " + nd + " " + ng + " " + ns + " " + nb + " " + model + "\n";
}

std::string NetlistGenerator::generateBSource(const std::string& name, 
                                               const std::vector<std::string>& nodes,
                                               const std::string& type,
                                               const std::string& expression) {
    if (nodes.size() < 2) return "";
    
    std::ostringstream oss;
    oss << "B" << name << " " << nodes[0] << " " << nodes[1] 
        << " " << type << "={" << expression << "}\n";
    return oss.str();
}

std::string NetlistGenerator::generateBVoltage(const std::string& name,
                                                const std::string& nPlus,
                                                const std::string& nMinus,
                                                const std::string& expression) {
    return generateBSource(name, {nPlus, nMinus}, "V", expression);
}

std::string NetlistGenerator::generateBCurrent(const std::string& name,
                                                const std::string& nPlus,
                                                const std::string& nMinus,
                                                const std::string& expression) {
    return generateBSource(name, {nPlus, nMinus}, "I", expression);
}

// E-source (Voltage-Controlled Voltage Source)
std::string NetlistGenerator::generateESource(const std::string& name,
                                               const std::string& nPlus,
                                               const std::string& nMinus,
                                               const std::string& cnPlus,
                                               const std::string& cnMinus,
                                               double gain) {
    std::ostringstream oss;
    oss << "E" << name << " " << nPlus << " " << nMinus << " "
        << cnPlus << " " << cnMinus << " " << gain << "\n";
    return oss.str();
}

// F-source (Current-Controlled Current Source)
std::string NetlistGenerator::generateFSource(const std::string& name,
                                               const std::string& nPlus,
                                               const std::string& nMinus,
                                               const std::string& vSourceName,
                                               double gain) {
    std::ostringstream oss;
    oss << "F" << name << " " << nPlus << " " << nMinus << " "
        << vSourceName << " " << gain << "\n";
    return oss.str();
}

// G-source (Voltage-Controlled Current Source)
std::string NetlistGenerator::generateGSource(const std::string& name,
                                               const std::string& nPlus,
                                               const std::string& nMinus,
                                               const std::string& cnPlus,
                                               const std::string& cnMinus,
                                               double transconductance) {
    std::ostringstream oss;
    oss << "G" << name << " " << nPlus << " " << nMinus << " "
        << cnPlus << " " << cnMinus << " " << transconductance << "\n";
    return oss.str();
}

// H-source (Current-Controlled Voltage Source)
std::string NetlistGenerator::generateHSource(const std::string& name,
                                               const std::string& nPlus,
                                               const std::string& nMinus,
                                               const std::string& vSourceName,
                                               double transresistance) {
    std::ostringstream oss;
    oss << "H" << name << " " << nPlus << " " << nMinus << " "
        << vSourceName << " " << transresistance << "\n";
    return oss.str();
}

std::string NetlistGenerator::generateSubcktInstance(const std::string& name,
                                                      const std::string& subcktName,
                                                      const std::vector<std::string>& nodes,
                                                      const std::map<std::string, double>& params) {
    std::ostringstream oss;
    oss << "X" << name << " ";
    
    for (const auto& node : nodes) {
        oss << node << " ";
    }
    
    oss << subcktName;
    
    for (const auto& [pname, pvalue] : params) {
        oss << " " << pname << "=" << valueToSpice(pvalue);
    }
    
    oss << "\n";
    return oss.str();
}

std::string NetlistGenerator::getInternalNode(const std::string& name) {
    auto it = m_nodeMap.find(name);
    if (it != m_nodeMap.end()) {
        return "n" + std::to_string(it->second);
    }
    
    int nodeNum = m_nodeCounter++;
    m_nodeMap[name] = nodeNum;
    return "n" + std::to_string(nodeNum);
}

std::string NetlistGenerator::expressionToSpice(ExprAST* expr) {
    // Simplified expression conversion
    // Full implementation would recursively convert AST to SPICE expression
    
    if (!expr) return "0";
    
    // Would need to handle different expression types
    return "0";
}

std::string NetlistGenerator::valueToSpice(double value) {
    std::ostringstream oss;
    
    // Use engineering notation
    if (value >= 1e9) {
        oss << (value / 1e9) << "G";
    } else if (value >= 1e6) {
        oss << (value / 1e6) << "Meg";
    } else if (value >= 1e3) {
        oss << (value / 1e3) << "k";
    } else if (value >= 1) {
        oss << value;
    } else if (value >= 1e-3) {
        oss << (value * 1e3) << "m";
    } else if (value >= 1e-6) {
        oss << (value * 1e6) << "u";
    } else if (value >= 1e-9) {
        oss << (value * 1e9) << "n";
    } else if (value >= 1e-12) {
        oss << (value * 1e12) << "p";
    } else {
        oss << value;
    }
    
    return oss.str();
}

} // namespace Flux
