/* Copyright 2026 Janada Sroor
 SPDX-License-Identifier: Apache-2.0
 http://www.apache.org/licenses/LICENSE-2.0
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
     http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License. */

#include "flux/compiler/schematic_ast.h"
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>

namespace Flux {

// ============ KiCad Schematic Generator ============

class KiCadSchematicGenerator
{
public:
    static bool generate(const SchematicExprAST& schematic, const std::string& outputFile);
    static bool generateSPICE(const SchematicExprAST& schematic, const std::string& outputFile);

private:
    static void writeKiCadHeader(std::ofstream& file);
    static void writeKiCadComponent(std::ofstream& file, const SchematicComponent& comp, int x, int y);
    static void writeKiCadWire(std::ofstream& file, int x1, int y1, int x2, int y2);
    static void writeKiCadLabel(std::ofstream& file, const std::string& text, int x, int y);
};

bool KiCadSchematicGenerator::generate(const SchematicExprAST& schematic, const std::string& outputFile)
{
    std::ofstream file(outputFile);
    if (!file.is_open()) {
        std::cerr << "[KiCad] Error: Cannot open " << outputFile << std::endl;
        return false;
    }

    std::cout << "[KiCad] Generating schematic: " << outputFile << std::endl;

    writeKiCadHeader(file);

    // Place components in a grid
    int x = 100;
    int y = 100;
    int xStep = 150;
    int yStep = 100;

    std::map<std::string, std::pair<int, int>> componentPositions;

    // Write components
    for (const auto& comp : schematic.getComponents()) {
        componentPositions[comp.Name] = {x, y};
        writeKiCadComponent(file, comp, x, y);
        x += xStep;
        if (x > 600) {
            x = 100;
            y += yStep;
        }
    }

    // Write connections
    for (const auto& conn : schematic.getConnections()) {
        auto fromIt = componentPositions.find(conn.FromComponent);
        auto toIt = componentPositions.find(conn.ToComponent);

        if (fromIt != componentPositions.end() && toIt != componentPositions.end()) {
            writeKiCadWire(file, fromIt->second.first + 50, fromIt->second.second, toIt->second.first,
                           toIt->second.second);

            if (!conn.NetName.empty()) {
                int midX = (fromIt->second.first + toIt->second.first) / 2;
                int midY = (fromIt->second.second + toIt->second.second) / 2;
                writeKiCadLabel(file, conn.NetName, midX, midY - 20);
            }
        }
    }

    // Write ports
    for (const auto& port : schematic.getPorts()) {
        std::cout << "[KiCad] Port: " << port.Name << " (" << port.Type << ")" << std::endl;
    }

    file << ")\n";
    file.close();

    std::cout << "[KiCad] Schematic generated: " << schematic.getComponents().size() << " components, "
              << schematic.getConnections().size() << " connections" << std::endl;

    return true;
}

bool KiCadSchematicGenerator::generateSPICE(const SchematicExprAST& schematic, const std::string& outputFile)
{
    std::ofstream file(outputFile);
    if (!file.is_open()) {
        std::cerr << "[SPICE] Error: Cannot open " << outputFile << std::endl;
        return false;
    }

    std::cout << "[SPICE] Generating netlist: " << outputFile << std::endl;

    file << "* SPICE Netlist generated by FluxScript\n";
    file << "* Schematic: " << schematic.getName() << "\n\n";

    // Write components
    for (const auto& comp : schematic.getComponents()) {
        file << comp.Name << " ";

        // Find connected nets
        std::vector<std::string> nets;
        for (const auto& conn : schematic.getConnections()) {
            if (conn.FromComponent == comp.Name) {
                nets.push_back(conn.NetName.empty() ? "N_" + conn.ToComponent + "_" + conn.ToPin : conn.NetName);
            }
            if (conn.ToComponent == comp.Name) {
                nets.push_back(conn.NetName.empty() ? "N_" + conn.FromComponent + "_" + conn.FromPin : conn.NetName);
            }
        }

        // Default to ground if no connections
        while (nets.size() < 2)
            nets.push_back("0");

        for (const auto& net : nets) {
            file << net << " ";
        }

        file << comp.Type << " " << comp.Value << "\n";
    }

    file << "\n.end\n";
    file.close();

    std::cout << "[SPICE] Netlist generated successfully" << std::endl;
    return true;
}

void KiCadSchematicGenerator::writeKiCadHeader(std::ofstream& file)
{
    file << "(kicad_sch (version 20211123) (generator fluxscript)\n";
    file << "  (uuid \"00000000-0000-0000-0000-000000000000\")\n";
    file << "  (paper \"A4\")\n";
    file << "  (lib_symbols\n";
    file << "  )\n";
    file << "  (symbols\n";
}

void KiCadSchematicGenerator::writeKiCadComponent(std::ofstream& file, const SchematicComponent& comp, int x, int y)
{
    file << "    (symbol \"" << comp.Name << "\" (at " << x << " " << y << " 0) "
         << "(unit 1) (in_bom yes) (on_board yes)\n";
    file << "      (property \"Reference\" \"" << comp.Name << "\" (id 0) (at " << (x - 20) << " " << (y - 20)
         << " 0))\n";
    file << "      (property \"Value\" \"" << comp.Value << "\" (id 1) (at " << (x - 20) << " " << (y + 20) << " 0))\n";
    file << "      (property \"Footprint\" \"" << comp.Footprint << "\" (id 2) (at " << x << " " << (y + 40)
         << " 0))\n";
    file << "    )\n";
}

void KiCadSchematicGenerator::writeKiCadWire(std::ofstream& file, int x1, int y1, int x2, int y2)
{
    file << "    (wire (pts (xy " << x1 << " " << y1 << ") (xy " << x2 << " " << y2 << ")) "
         << "(stroke (width 0) (type default) (color 0 0 0 0)))\n";
}

void KiCadSchematicGenerator::writeKiCadLabel(std::ofstream& file, const std::string& text, int x, int y)
{
    file << "    (label \"" << text << "\" (at " << x << " " << y << " 0) "
         << "(fields_autoplaced yes) (uuid \"00000000-0000-0000-0000-000000000000\")\n";
    file << "      (effects (font (size 1.27 1.27)))\n";
    file << "    )\n";
}

// ============ AST Codegen Implementation ============

TypedValue SchematicExprAST::codegen(CodegenContext& context)
{
    // Generate schematic as KiCad format by default
    std::string outputFile = getName() + ".kicad_sch";
    bool success = KiCadSchematicGenerator::generate(*this, outputFile);

    if (!success) {
        std::cerr << "[CodeGen] Failed to generate schematic" << std::endl;
    }

    // Also generate SPICE netlist
    std::string spiceFile = getName() + ".cir";
    KiCadSchematicGenerator::generateSPICE(*this, spiceFile);

    return TypedValue(llvm::ConstantFP::get(context.TheContext, llvm::APFloat(success ? 1.0 : 0.0)), TypeKind::Double);
}

TypedValue ExportSchematicExprAST::codegen(CodegenContext& context)
{
    std::cout << "[Export] Exporting schematic '" << SchematicName << "' to " << OutputFile << " (format: " << Format
              << ")" << std::endl;

    // This would need access to the schematic AST
    // For now, just print the export command
    return TypedValue(llvm::ConstantFP::get(context.TheContext, llvm::APFloat(1.0)), TypeKind::Double);
}

} // namespace Flux
