/* Copyright 2026 Janada Sroor
 SPDX-License-Identifier: Apache-2.0
 http://www.apache.org/licenses/LICENSE-2.0
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
     http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License. */

#ifndef FLUX_JIT_H
#define FLUX_JIT_H

// Undefine Qt's emit macro before including LLVM headers
// Qt defines 'emit' as a macro which conflicts with LLVM-18's Orc JIT layer
#ifdef emit
#undef emit
#endif

#include <llvm/Config/llvm-config.h>
#include <llvm/ExecutionEngine/Orc/LLJIT.h>
#include <llvm/IR/Module.h>
#include <llvm/Passes/PassBuilder.h>
#include <llvm/Support/MemoryBuffer.h>
#if LLVM_VERSION_MAJOR >= 22
#include <llvm/Plugins/PassPlugin.h>
#else
#include <llvm/Passes/PassPlugin.h>
#endif
#include <atomic>
#include <chrono>
#include <functional>
#include <llvm/Bitcode/BitcodeReader.h>
#include <llvm/Bitcode/BitcodeWriter.h>
#include <llvm/ExecutionEngine/Orc/ExecutionUtils.h>
#include <llvm/IR/DataLayout.h>
#include <llvm/IR/LLVMContext.h>
#include <llvm/Transforms/Utils/Cloning.h>
#include <memory>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

namespace Flux {

enum class OptimizationLevel
{
    O0, // No optimization
    O1, // Basic optimizations
    O2, // Moderate optimizations
    O3  // Aggressive optimizations
};

struct SIMDOptions
{
    bool enableLoopVectorization = true; // Enable loop vectorizer
    bool enableSLPVectorization = true;  // Enable SLP (Superword-Level Parallelism) vectorizer
    bool enableInterleavedAccess = true; // Enable interleaved memory access optimization
    int vectorizationFactor = 0;         // 0 = auto, otherwise specify factor (2, 4, 8, etc.)
};

struct TCOOptions
{
    bool enableTailCallElimination = true; // Enable tail call optimization
    bool enableTailCallMerging = true;     // Enable tail call merging for mutual recursion
    int maxRecursionDepth = 0;             // 0 = unlimited (with TCO), otherwise limit depth
};

// ============================================================================
// Profile-Guided Optimization (PGO) Infrastructure
// ============================================================================

// A single profiling sample: which function was called with what argument hints
struct ProfilingSample
{
    std::string functionName;
    double totalTimeUs = 0.0;
    int invocationCount = 0;
    int optLevelAtSample = 0; // O0..O3 at the time of sampling
    bool isSynthetic = false; // true if generated by offline replay
};

// Per-function execution profile
struct FunctionProfile
{
    std::string name;
    int totalCalls = 0;
    int totalExits = 0;
    double totalCpuTimeUs = 0.0;
    double minCpuTimeUs = 1e18;
    double maxCpuTimeUs = 0.0;
    OptimizationLevel currentOptLevel = OptimizationLevel::O0;
    OptimizationLevel bestOptLevel = OptimizationLevel::O0;

    // Edge frequencies: (fromBlock, toBlock) -> count
    // Used for branch probability metadata on recompile
    std::vector<std::pair<std::pair<uint64_t, uint64_t>, uint64_t>> edgeCounts;

    void recordCall(double elapsedUs)
    {
        totalCalls++;
        totalCpuTimeUs += elapsedUs;
        if (elapsedUs < minCpuTimeUs)
            minCpuTimeUs = elapsedUs;
        if (elapsedUs > maxCpuTimeUs)
            maxCpuTimeUs = elapsedUs;
    }

    double averageTimeUs() const { return totalCalls > 0 ? totalCpuTimeUs / totalCalls : 0.0; }
};

// PGO profiler attached to each FluxJIT instance
class PGOProfiler
{
public:
    // Record a function call and its elapsed time
    void recordCall(const std::string& name, double elapsedUs, OptimizationLevel optLevel);

    // Get profile for a specific function
    FunctionProfile* getProfile(const std::string& name);
    const FunctionProfile* getProfile(const std::string& name) const;

    // Get all known profiles
    std::unordered_map<std::string, FunctionProfile> getAllProfiles() const;

    // Classify a function based on profiling data
    enum class Hotness
    {
        Cold,
        Warm,
        Hot,
        VeryHot
    };
    Hotness classifyFunction(const std::string& name) const;

    // Get suggested optimization level based on profile
    OptimizationLevel suggestOptLevel(const std::string& name) const;

    // Annotate LLVM function with profiling metadata (branch weights, etc.)
    // before recompilation
    void annotateFunction(llvm::Function* F, const FunctionProfile& profile);

    // Reset all profiles
    void reset();

    // Import/export profiles for offline analysis
    bool exportProfiles(const std::string& filepath) const;
    bool importProfiles(const std::string& filepath);

private:
    mutable std::mutex m_mutex;
    std::unordered_map<std::string, FunctionProfile> m_profiles;
};

// ============================================================================
// Kernel Auto-Tuner
// ============================================================================

struct BenchmarkResult
{
    std::string functionName;
    OptimizationLevel optLevel;
    double avgTimeUs;
    double minTimeUs;
    double maxTimeUs;
    int samples;
    bool valid;
};

class KernelAutoTuner
{
public:
    // Benchmark a function pointer at the given optimization level.
    // Calls the function `numSamples` times with synthetic inputs and
    // measures execution time.
    BenchmarkResult benchmarkFunction(const std::string& name, void* funcPtr, OptimizationLevel level,
                                      int numSamples = 100);

    // Find the best optimization level for a function by benchmarking
    // each level and picking the fastest.
    OptimizationLevel findBestOptLevel(const std::string& name, const std::vector<BenchmarkResult>& results);

    // Auto-tune a function: benchmark each available opt level (O1, O2, O3)
    // and return the best pointer + level.
    struct TuneResult
    {
        void* funcPtr = nullptr;
        OptimizationLevel bestLevel = OptimizationLevel::O0;
        std::vector<BenchmarkResult> benchmarks;
    };

    TuneResult autoTuneFunction(const std::string& name,
                                const std::vector<void*>& optFuncPtrs // [O0, O1, O2, O3] or nullptr if unavailable
    );

    void setNumBenchmarkSamples(int n) { m_numSamples = n; }
    int getNumBenchmarkSamples() const { return m_numSamples; }

private:
    int m_numSamples = 100;
    mutable std::mutex m_mutex;
};

class FluxJIT
{
public:
    FluxJIT(OptimizationLevel optLevel = OptimizationLevel::O2);
    ~FluxJIT();

    void addModule(std::unique_ptr<llvm::Module> M, std::unique_ptr<llvm::LLVMContext> Ctx);
    void addObjectFile(std::unique_ptr<llvm::MemoryBuffer> ObjectBuffer);
    void* getPointerToFunction(const std::string& Name);
    void registerFunction(const std::string& Name, void* FuncPtr);

    void setOptimizationLevel(OptimizationLevel level);
    OptimizationLevel getOptimizationLevel() const { return m_optLevel; }

    // --- Tiered JIT API ---
    void* promoteFunction(const std::string& Name, OptimizationLevel targetLevel);
    void setAutoPromoteThreshold(int n) { m_autoPromoteThreshold = n; }
    int getAutoPromoteThreshold() const { return m_autoPromoteThreshold; }
    int getCallCount(const std::string& Name) const;
    void resetCallCounts();
    bool isPromoted(const std::string& Name) const;

    void setSIMDOptions(const SIMDOptions& options);
    SIMDOptions getSIMDOptions() const;

    void setTCOOptions(const TCOOptions& options);
    TCOOptions getTCOOptions() const;

    const llvm::DataLayout& getDataLayout() const { return m_dataLayout; }
    const std::string& getTargetTriple() const { return m_targetTriple; }

    // --- PGO API ---
    PGOProfiler& getProfiler() { return m_pgoProfiler; }
    const PGOProfiler& getProfiler() const { return m_pgoProfiler; }

    // --- Kernel Auto-Tuner API ---
    KernelAutoTuner& getAutoTuner() { return m_autoTuner; }
    const KernelAutoTuner& getAutoTuner() const { return m_autoTuner; }

    // Enable/disable instrumentation for profiling
    void setProfilingEnabled(bool enabled) { m_profilingEnabled = enabled; }
    bool isProfilingEnabled() const { return m_profilingEnabled; }

    // Run auto-tuning on the current set of promoted hot functions
    int autoTuneHotFunctions();

private:
    void registerNativeFunctions();
    void registerComplexHelpers();
    void registerMathHelpers();
    void optimizeModule(llvm::Module* M, OptimizationLevel level);
    void prepareModule(llvm::Module& M);
    bool redirectFunction(const std::string& Name, void* oldAddr, void* newAddr);
    void applySIMDToPassBuilder(llvm::ModulePassManager& MPM, llvm::FunctionPassManager& FPM);

    std::unique_ptr<llvm::orc::LLJIT> m_lljit;
    std::unique_ptr<llvm::PassBuilder> m_passBuilder;
    llvm::orc::JITDylib* m_runtimeDylib = nullptr;
    llvm::DataLayout m_dataLayout;
    std::unique_ptr<llvm::TargetMachine> m_targetMachine;
    std::string m_targetTriple;
    OptimizationLevel m_optLevel;
    SIMDOptions m_simdOptions;
    TCOOptions m_tcoOptions;

    // Eagerly compiled function pointer cache (avoids ORC lazy materialization issues)
    std::unordered_map<std::string, void*> m_functionPtrs;
    mutable std::mutex m_fnMapMutex;

    // --- Tiered JIT data ---
    static constexpr int DEFAULT_HOT_THRESHOLD = 10;
    int m_autoPromoteThreshold = DEFAULT_HOT_THRESHOLD;

    // Saved original function IR (bitcode) for recompilation
    struct SavedModule
    {
        std::string bitcode;
        std::vector<std::string> functionNames;
    };
    std::vector<SavedModule> m_savedModules;

    // Per-function call counters
    std::unordered_map<std::string, std::atomic<int>> m_callCounts;

    // Promoted function cache (O3 compiled pointers)
    std::unordered_map<std::string, void*> m_promotedPtrs;

    // PGO profiler
    PGOProfiler m_pgoProfiler;
    bool m_profilingEnabled = false;

    // Kernel auto-tuner
    KernelAutoTuner m_autoTuner;
};

} // namespace Flux

#endif // FLUX_JIT_H
